#!/bin/sh
#PBS -N pytorchmain
#PBS -q gpu
#PBS -l walltime=00:50:00,mem=400mb,nodes=1:ppn=1
#PBS -V

# User Directives
#module load python3
#module load miniconda3
#cd $PBS_O_WORKDIR
export PATH="home/mt1/15CS60R20/miniconda3/envs/py36/bin:$PATH"
which python
cd /home/mt1/15CS60R20/Meher/Question_question_relatedness/
python main.py -to_preprocess_train True -to_preprocess_test True
#python main.py -mode only_test -name_train large_link_prediction_train_NEW_shuffled_preprocessed.csv -name_val large_link_prediction_dev_NEW_shuffled_preprocessed.csv -name_test test_sample.csv -to_preprocess_test True -model_path Expt_results/checkpoints/checkpoint.pt
#End of script

